config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users' }

  root "tracks#recently_played_index"

  resources :playlists do
    collection do
      get 'fetch_all'
    end
    member do
      get :download
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get :recently_played_index
      get :download
    end
    member do
      get :play
      get :stream
    end
  end
  resources :artists, only: [:index, :show]


  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "home/index", to: "home#index" # /api/v1/home/index
        resources :playlists, only: [:index, :show]
      end
    end
  end

end

app/models/track.rb
# frozen_string_literal: true

class Track < ApplicationRecord
  belongs_to :album
  has_and_belongs_to_many :artists
  has_many :playlist_tracks

  # Die Playlist die diesen Track enthlten
  has_many :playlists, through: :playlist_tracks

  def dauer
    Time.at(duration_ms / 1000).utc.strftime('%M:%S')
  end

  # Siehe @RSpotify::Audiofeatures
  # - acousticness:     [Float] danceability Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.
  # - mode:             Major, Minor (Oder 1 und 0)
  # - energy:           Float
  # - instrumentalness  Float
  # - liveness          Float
  # - loudness          Float
  # - speechiness       [Float] tempo The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.
  # - time_signature    Integer
  # - valence           Float
  #
  # - duration_ms
  # - analysis_url
  # - key
  # - href
  # - id
  # - type
  # - uri
  def af
    @af ||= audio_features.present? ? JSON.parse(audio_features, object_class: OpenStruct) : nil
  end

  def energy
    af.try(:energy)
  end

  def tempo
    af.try(:tempo)
  end

  # Das Genre, wird aus dem runtergeladenen File gelesen
  def genre
    return unless track_path
    begin
      WahWah.open(track_path).genre
    rescue
      # kann irgendwie nil sein.
      nil
    end
  end

  # @return den Pfad zum rungereladenen Lied. Wird aus dem Namen des Tracks bestimmt.
  # Gewisse Zeichen werden im Pfad nicht oder anders verwendet, darum zuerst ersetzen.
  # Der Interpret ist meistens im Namen des Files auch vorhanden. Wird hier nicht berücksichtigt.
  def track_path
    search = name

    replacements = { ':' => '-', '?' => '', '/' => '', '"' => '\'', '[' => '\[', ']' => '\]' }
    search.gsub!(Regexp.union(replacements.keys), replacements)
    dir_name = Rails.root.join('downloads/tracks')
    Dir.chdir dir_name
    files = Dir.glob("*-?#{search}.m4a")
    if files.first
      # Rails.logger.info("File gefunden: #{search}")
    else
      Rails.logger.info("!!File nicht gefunden: #{search}")
    end
    files.first
  end

  # {"acousticness"=>0.552, "analysis_url"=>"https://api.spotify.com/v1/audio-analysis/2uSavRrWjouarU9DupcWmK", "danceability"=>0.69, "duration_ms"=>296333, "energy"=>0.553, "instrumentalness"=>0.914, "key"=>5, "liveness"=>0.121, "loudness"=>-12.152, "mode"=>1, "speechiness"=>0.0372, "tempo"=>131.674, "time_signature"=>4, "track_href"=>"https://api.spotify.com/v1/tracks/2uSavRrWjouarU9DupcWmK", "valence"=>0.917, "external_urls"=>nil, "href"=>nil, "id"=>"2uSavRrWjouarU9DupcWmK", "type"=>"audio_features", "uri"=>"spotify:track:2uSavRrWjouarU9DupcWmK"}
end

app/controllers/tracks_controller.rb
# frozen_string_literal: true

class TracksController < ApplicationController
  # Zeigt die letzten 50 gespielte Lieder
  # tracks sind RSpotify::Track
  def recently_played_index
    @tracks = current_user.spotify_user.recently_played(limit: 50) #=>
  end

  def index
    @tracks = Track.includes(:artists, :playlists, :album).order(:name)
  end

  def download
    tracks_without_file = []
    Track.all.each do |t|
      path = t.track_path
      tracks_without_file << t unless path
    end

    service = DownloadTrackService.new(tracks_without_file)
    service.download
    redirect_to tracks_path
  end

  def show
    id = params[:id]
    @track = Track.find(id)
    # @spotify_track = RSpotify::Track.find ([@track.spotify_id]).first
  end

  # Spielt den Track in Spotify. Funktioniert leider nicht. Es gibt einen RestClient::Unauthorized (401 Unauthorized)
  # Habe abgerochen. Infos siehe https://www.rubydoc.info/github/guilhermesad/rspotify/master/RSpotify/Player#play_track-instance_method
  def play
    id = params[:id]
    track = Track.find(id)
    uri = "spotify:track:#{track.spotify_id}"
    player = RSpotify::Player.new(current_user.spotify_user)
    player.play_track(nil, uri)
    head :ok
  end

  def stream
    id = params[:id]
    track = Track.find(id)
    track_path = track.track_path
    if track_path
      send_file track_path
    end
    # head :no_content
  end

end

app/views/tracks/_track.erb
<%# Repräsentiert einen Eintrag in der Tabelle %>
<tr>
  <th scope="row"><%= link_to(track.name, track_path(track.id)) %></th>
  <td>
    <%= track.dauer %>
  </td>
  <td> <%= track.genre %> </td>
  <td>
    <%= track.popularity %>
  </td>
  <td>
    <%= engergie_to_view track.energy %>
  </td>
  <td>
    <%= tempo_to_view track.tempo %>
  </td>

  <td>
    <% track.artists.each do |a| %>
      <%= link_to a.name, artist_path(a.id) %>
    <% end %>
  </td>
  <td>
    <%= track.album.name %>
  </td>
  <td>
    <%= l track.album.release_date if track.album.release_date %>
  </td>
  <td>
    <% track.playlist_tracks.each do |pt| %>
      <%= link_to playlist_path(pt.playlist.id) do %>
        <span class="badge <%= pt.playlist.color_class %>"><%= pt.playlist.short_name %></span>
      <% end %>
    <% end %>
  </td>

  <td>
    <%= render partial: 'components/audio_file', locals: {track: track} %>
  </td>
</tr>

app/views/tracks/_tracks.erb
<table class="table caption-top">
  <caption>Tracks</caption>
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Dauer</th>
    <th scope="col">Genre</th>
    <th scope="col">Bekanntheit</th>
    <th scope="col">Energie</th>
    <th scope="col">Tempo</th>
    <th scope="col">Künstler</th>
    <th scope="col">Album Name</th>
    <th scope="col">Release Date</th>
    <th scope="col">Playlists</th>
  </tr>
  </thead>
  <tbody>
  <%= render tracks %>
  </tbody>
</table>

app/views/tracks/index.html.erb
<%= link_to(" download_files", download_tracks_path)  %>

<h1>Meine Tracks</h1>

<%= render 'tracks', tracks: @tracks %>

app/views/tracks/recently_played.html.erb
<h1>Meine zuletzt gespielten Stücke</h1>

<ul>
<% @recently_played_tracks.each do |p| %>
  <li>
    <%= l(Time.zone.parse(p.played_at)) %> |
    <%# p.context_type %>
    <%= p.popularity %>  |
    <%= p.name %>, |
    <%= p.artists.map(&:name).join(", ") %>|
    <%= p.album.name %>  |
    <%# p.album.genres.join(", ") Teuer!!%>
  </li>
<% end %>
</ul>

app/views/tracks/recently_played_index.html.erb
<h1>Meine zuletzt gespielten Stücke</h1>

<ul>
<% @tracks.each do |p| %>
  <li>
    <%= l(Time.zone.parse(p.played_at)) %> |
    <%# p.context_type %>
    <%= p.popularity %>  |
    <%= p.name %>, |
    <%= p.artists.map(&:name).join(", ") %>|
    <%= p.album.name %>  |
    <%# p.album.genres.join(", ") Teuer!!%>
  </li>
<% end %>
</ul>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<div> aus: <%= @track.album.name %> | <%= @track.album.release_date ? l(@track.album.release_date) : nil %></div>
<div><a href="<%= @track.url %>">Track in Spotify hören</a></div>
<div>
  <%= render partial: 'components/audio_file', locals: {track: @track}  %>
</div>
<div>
  <%= render partial: 'components/spotify_player', locals: {track: @track} %>
</div>

<div>
    Genre: <%= @track.genre%>
</div>

<br>
  <table class="table caption-top">
    <caption>Künstler</caption>
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Bekanntheit</th>
      <th scope="col">Anzahl Tracks</th>
    </tr>
    </thead>
    <tbody>
    <%= render @track.artists %>
    </tbody>
  </table>

<div> Die Künstler des Albums</div>
<% @track.album.artists.each do |a| %>
  <a><%= link_to a.name, artist_path(a.id)  %></a>
<% end %>


<br>
<br>


<% if @track.af.present? %>
  <ul>
    <li> Acousticness: <%= @track.af.acousticness %>   </li>
    <li> Danceability: <%= @track.af.danceability %>   </li>
    <li> Energy: <%= @track.af.energy %>   </li>
    <li> Mode: <%= @track.af.mode == 1 ? "Major" : "Minor" %>   </li>
    <li> time_signature: <%= @track.af.time_signature %>   </li>
    <li> Tempo: BPM <%= @track.af.tempo %>  </li>
    <li> instrumentalness: <%= @track.af.instrumentalness %>  </li>
    <li> liveness: <%= @track.af.liveness %>  </li>
    <li> loudness: <%= @track.af.loudness %>  </li>
    <li> valence: <%= @track.af.valence %>  </li>
  </ul>
<% end %>


<table class="table caption-top">
  <caption>Playlists die diesen Track enthalten</caption>
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Sichtbarkeit</th>
    <th scope="col">Anzahl Tracks</th>
    <th scope="col">Download</th>
  </tr>
  </thead>
  <tbody>
  <%= render @track.playlists %> <%# magischerweise weiss Rails wie rendern. Nämlich mit playlists/_playlist.erb %>
  </tbody>
</table>