config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users' }

  root "tracks#recently_played_index"

  resources :playlists do
    collection do
      get 'fetch_all'
    end
    member do
      get :download
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get :recently_played_index
      get :download
    end
    member do
      get :play
      get :stream
    end
  end
  resources :artists, only: [:index, :show]


  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "home/index", to: "home#index" # /api/v1/home/index
        resources :playlists, only: [:index, :show]
      end
    end
  end

end

app/models/playlist_track.rb
# frozen_string_literal: true

# Eine JoinTabelle mit der zusätzlichen Information, wann der Track zur Playlist hinzgefügt wurde (:added_at)
class PlaylistTrack < ApplicationRecord
  belongs_to :playlist
  belongs_to :track
end

app/views/playlist_tracks/_playlist_track.erb
<%# Repräsentiert eine Playlist Track Eintrag in der Tabelle der Playlist %>
<tr>
  <th scope="row"><%= link_to playlist_track.track.name, track_path(playlist_track.track.id) %> </th>
  <td> <%= playlist_track.track.dauer %> </td>
  <td> <%= l(playlist_track.added_at.to_date) %> </td>
  <td> <%= (playlist_track.track.genre) %> </td>
  <td><%= playlist_track.track.popularity %></td>
  <td><%= engergie_to_view playlist_track.track.energy %></td>
  <td><%= tempo_to_view playlist_track.track.tempo %></td>
  <td>
    <% playlist_track.track.artists.each do |a| %>
      <%= link_to a.name, artist_path(a.id) %>
    <% end %>
  </td>
  <td> <%= playlist_track.track.album.name %></td>
  <td> <%= l playlist_track.track.album.release_date if playlist_track.track.album.release_date %></td>

  <td>
    <% playlist_track.track.playlist_tracks.each do |pt| %>
      <% unless pt.id == playlist_track.id %>
        <%= link_to playlist_path(pt.playlist.id) do %>
          <span class="badge <%= pt.playlist.color_class %>"><%= pt.playlist.short_name %></span>
        <% end %>
      <% end %>
    <% end %>
  </td>
  <td>
    <%= render partial: 'components/audio_file', locals: {track: playlist_track.track} %>
    <% #= render partial: 'components/spotify_player', locals: {track: playlist_track.track} %>
  </td>
</tr>