config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users' }

  root "tracks#recently_played_index"

  resources :playlists do
    collection do
      get 'fetch_all'
    end
    member do
      get :download
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get :recently_played_index
      get :download
    end
    member do
      get :play
      get :stream
    end
  end
  resources :artists, only: [:index, :show]


  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "home/index", to: "home#index" # /api/v1/home/index
        resources :playlists, only: [:index, :show]
      end
    end
  end

end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  has_many :playlist_tracks
  has_many :tracks, through: :playlist_tracks

  COLORS = %i[green blue yellow red lila orange black brown].freeze
  CONTEXT = [
    'bg-primary',
    'bg-secondary',
    'bg-success',
    'bg-danger',
    'bg-warning',
    'bg-info',
    "bg-light",
  ].freeze

  COLORS_TO_CONTEXT = {
    green: 'bg-success',
    blue: 'bg-primary',
    yellow: 'bg-warning',
    red: 'bg-danger',
    lila: 'bg-info',
    orange: 'bg-secondary',
    xyz: 'bg-dark'
  }.freeze



  def color_class
    select_color short_name
  end

  # def short_name
  #   n = name.remove('Fusion')
  #   n = n.remove('fusion')
  #   n.strip
  # end

  #Um die Groß- und Kleinschreibung zu ignorieren, nutzen wir einen regulären Ausdruck mit dem i-Flag.
  def short_name
    name.gsub(/\bfusion\b/i, '_F_') # \b Wortgrenze
       .gsub(/\bblues\b/i, '_B_')
      .gsub(/\s+/, '')
      .gsub(/_+/, '_')
      .gsub(/\A_+/, '')
      .gsub(/_+\z/, '')

  end

  def name_path_ready
    name.delete(' ')
  end

  private

  def calculate_checksum(str)
    checksum = 0
    str.each_byte do |byte|
      checksum += byte
    end
    checksum
  end

  def select_color(str)
    if is_a_dj_playlist? str
      'bg-dark'
    else
      checksum = calculate_checksum(str)
      CONTEXT[checksum % CONTEXT.length]
    end
  end

  def is_a_dj_playlist?(str)
    /^\d{4}/.match?(str)
  end
end

app/controllers/api/v1/playlists_controller.rb
# frozen_string_literal: true

module Api
  # noinspection RubyClassModuleNamingConvention
  module V1
    class PlaylistsController < Api::V1::BaseController
      # Vorübergehend, damit ich die Tests besser schreiben kann
      # skip_before_action :authenticate

      def index
        @playlists = Playlist.order(:name)
        render json: @playlists
      end

      def show
        id = params[:id]
        @playlist = Playlist.find(id)
        render json: @playlist
      end
    end
  end
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  def fetch_all
    @info = BuildMusicNetService.new(current_user).build
  end

  def index
    @playlists = Playlist.order(:name)
  end

  def show
    id = params[:id]
    @playlist = Playlist.find(id)
    @playlist_tracks = @playlist.playlist_tracks.includes(track: { album: :artists })
  end

  def edit
    id = params[:id]
    @playlist = Playlist.find(id)
  end

  def update
    id = params[:id]
    @playlist = Playlist.find(id)
    @playlist.save!
    redirect_to playlists_path
  end

  # Lädt alle Tracks der Plylist runter und zeigt dann diese Plylit an
  def download
    id = params[:id]
    @playlist = Playlist.find(id)
    service = DownloadPlaylistService.new(current_user, @playlist)
    service.download
    redirect_to playlist_path(id)
  end
end

app/views/playlists/_playlist.erb
<tr>

  <td>
    <%= link_to playlist_path(playlist.id) do %>
      <span class="badge <%= playlist.color_class %>"><%= playlist.short_name %></span>
    <% end %>
  </td>
  <td><%= playlist.public ? "öffentlich" : "privat" %></td>
  <td><%= playlist.tracks.count  %></td>
  <td><%= link_to(playlist.name, download_playlist_path(playlist.id))  %></td>
  <td><%= link_to("edit", edit_playlist_path(playlist))  %></td>
</tr>

app/views/playlists/_playlists.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col"
        id="playlists-name"
        data-reflex="click->Table#sort"
        data-column="name"
        data-direction="asc"
    >
      Name
    </th>
    <th scope="col">Sichtbarkeit</th>
    <th scope="col">Anzahl Tracks</th>
    <th scope="col">Download</th>
  </tr>
  </thead>
  <tbody>
  <%= render @playlists %>
  </tbody>
</table>

app/views/playlists/edit.html.erb
<%= bootstrap_form_for(@playlist) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "save" %>
<% end %>

app/views/playlists/fetch_all.html.erb
<h1>Alles geholt</h1>


<p><%= @info.hash  %></p>

app/views/playlists/index.html.erb
<script>

    document.addEventListener("turbo:load", function () {
        console.log("inner script");

      const container = document.querySelector('#example');

      const hot = new Handsontable(container, {
      data: [
      ['', 'Tesla', 'Volvo', 'Toyota', 'Ford'],
      ['2019', 10, 11, 12, 13],
      ['2020', 20, 11, 14, 13],
      ['2021', 30, 15, 12, 13]
      ],
      rowHeaders: true,
      colHeaders: true,
      height: 'auto',
      licenseKey: 'non-commercial-and-evaluation' // for non-commercial use only
      });

    });

</script>


<div id="example">

</div>

<h1>Meine Playlists</h1>

<%= render 'playlists', playlists: @playlists %>

app/views/playlists/my_playlists.html.erb
<h1>Meine Playlists</h1>

<ul>
  <%= render partial: 'playlist', collection: @playlists %> <%# der Shorthand render @playlists geht nicht, da playlist "is not an ActiveModel-compatible object. It must implement :to_partial_path."  %> %>
</ul>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

<div>  <%= link_to("Download Tracks", download_playlist_path(@playlist.id)) %>
</div>
<table class="table caption-top">
  <caption>Einträge</caption>
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Dauer</th>
    <th scope="col">hinzugefügt</th>
    <th scope="col">Genre</th>
    <th scope="col">Bekanntheit</th>
    <th scope="col">Energie</th>
    <th scope="col">Tempo</th>
    <th scope="col">Künstler</th>
    <th scope="col">Albumname</th>
    <th scope="col">Release Datum</th>
    <th scope="col">Playlists</th>
    <th scope="col" style="min-width: 90px">xxx </th>
    <%# p.album.genres.join(", ") Teuer!!%>
  </tr>
  </thead>
  <tbody>
    <%= render @playlist.playlist_tracks %>
  </tbody>
</table>