config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users' }

  root "tracks#recently_played_index"

  resources :playlists do
    collection do
      get 'fetch_all'
    end
    member do
      get :download
    end
  end

  resources :tracks, only: [:index, :show] do
    collection do
      get :recently_played_index
      get :download
    end
    member do
      get :play
      get :stream
    end
  end
  resources :artists, only: [:index, :show]


  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get "home/index", to: "home#index" # /api/v1/home/index
        resources :playlists, only: [:index, :show]
      end
    end
  end

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Musicnet</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to('Zuletzt gespielt', recently_played_index_tracks_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Playlists', playlists_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Tracks', tracks_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Artists', artists_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Fetch all Playlists!', fetch_all_playlists_path, class: "nav-link") %>
        </li>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <img src="<%= current_user.spotify_user.images.first["url"] %>" alt="avatar" style="width:48px;height:48px;">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        <% else %>
            <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        <% end %>      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicnet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>